# Generated by Django 2.1.2 on 2018-12-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fortune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
                ('fortune', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
