# Generated by Django 2.1.2 on 2018-12-23 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fortune',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=100)),
                ('fortune', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
