# Generated by Django 2.1.2 on 2018-12-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_fortune_cookie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortune',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
