# Generated by Django 2.1.2 on 2018-12-22 17:04

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('bad_fortune_cookie', '0002_auto_20181213_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortune',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
